### ISSUE TITLE
Korot installer bug

### ISSUE THREAD

**Issue by Metrohan** [Haltroy/Korot#1]
I tried to install Korot but after push the install button, installer give WebClient error.

**Comment by Haltroy** [comment]
Fixed in 1.0.3 version of installer.

**Comment by Metrohan** [comment]
It's not fixed. I tried again.

**Comment by Haltroy** [comment]
It seems like WebClient can't use the same folder as the Korot Installer uses 'cuz you have to be administrator for it.
If you see this problem and your Korot Installer version is below the 1.0.4 then please try running it in Administrator Mode or download the update from http://korot.haltroy.com

**Comment by Haltroy** [comment]
Fixed in 1.0.4 by making program only run in Administrator mode.
