### ISSUE TITLE
Support for notifications

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Korot#22]
- [x] Edit [`notification.js`](https://github.com/MrSwitch/notification.js/blob/master/notification.js) so it will send notifications by using `CefSharp.PostMessage` and receive notification permissions by reading `var korotNotificationPermission = '[grated/denied/unknown]'`.
 - [x] Show notifications by receiving them from `OnBrowserJavascriptMessageReceived` event.

**Comment by Haltroy** [comment]
I searched it on Google to find a working solution to this but couldn't find it. Also Cefsharp doesn't supports this feature right now.
Bıt this feature will be added when Cefsharp supports it.

**Comment by Haltroy** [comment]
I think this is possible by detecting it with JS handlers so I'm reopening it.

**Comment by Haltroy** [comment]
Any helps are welcome and I will put names of people who helped with this issue are going to be listed in About page.

**Comment by Haltroy** [comment]
[This](https://stackoverflow.com/questions/56561982/passing-on-a-web-notification-to-windows-notifications-with-cefsharp) can help.

**Comment by Haltroy** [comment]
I made a research but I couldn't get any results yet again. Even tried to add `CefSharp.PostMessage` (as mentioned in the answers which are linked to [this comment](https://github.com/Haltroy/Korot/issues/22#issuecomment-581933619).) but didn't worked.
Also, this is even a bigger upstream issue (not even CefSharp, CEF issue) and nobody seems to figure ir out to how to implement this.

**Comment by amaitland** [comment]
Notifications shouldn't be too hard to implement. What does your code look like? 

There are plenty of notification shims that should be a decent starting point. One example is https://github.com/MrSwitch/notification.js/blob/master/notification.js

**Comment by Haltroy** [comment]
> Notifications shouldn't be too hard to implement. What does your code look like?

Well, I tried but couldn't understand anything and now I'm trying to add it again.
You can check out the codes that I used for this project in [here](https://github.com/Haltroy/Korot/tree/master/Korot%20Desktop/Source%20Code).
Thanks for reminding me about this issue. I forgot to check it out.

**Comment by amaitland** [comment]
Is the source for your JavaScript polyfil somewhere in this repository?

**Comment by Haltroy** [comment]
> Is the source for your JavaScript polyfil somewhere in this repository?

Well, no but I'm going to add a branch ([`notificationTest`](https://github.com/Haltroy/Korot/tree/notificationsTest) ) that will include the codes in [MinimalExample Winforms JSB Demo](https://github.com/cefsharp/CefSharp.MinimalExample/tree/demo/javascriptbinding).

**Comment by Haltroy** [comment]
I added a test page for notification system.
I'm going to work on a system for showing the notification.

**Comment by amaitland** [comment]
You can use PostMessage to simplify this. There is an example at https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#JSEvent

Have you attempted to write a notification polyfil?

**Comment by Haltroy** [comment]
I've never heard the word `polyfil` in my entire life. (Since my primary language isn't English. Sorry about that.)
I added the example but how am I going to use this for [`Notification()`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification)?
###### (Sorry for asking this question if this is a stupid question. I have no brain. Literally none. That doesn't exists on my body.)
I added the UI part and now the only thing to left is connect these two (`Javascript Binding/PostMessage etc.` with `Notification class & frmNotification`).
I made a simple notification example in [`frmCEF`](https://github.com/Haltroy/Korot/blob/notificationsTest/Korot%20Desktop/Source%20Code/Forms/frmCEF.cs#L81).

**Comment by amaitland** [comment]
Typo on my part should be polyfill. See https://en.m.wikipedia.org/wiki/Polyfill_(programming)

You'll need to write some JavaScript to implement the notification API and inject it into every frame. 

I'll leave you to do your own additional research.

**Comment by Haltroy** [comment]
> ~Typo on my part should be polyfill.~ See https://en.m.wikipedia.org/wiki/Polyfill_(programming)

I used the [`notification.js`](https://github.com/MrSwitch/notification.js/blob/master/notification.js) and it did a pretty good job filling the hole but it's kinda buggy. 

     Uncaught TypeError: Cannot read property 'then' of undefined
      Notification.requestPermission().then(function (permission) {

Now, I'm going to edit the [`notification.js`](https://github.com/MrSwitch/notification.js/blob/master/notification.js) so it will send a new notification by using `CefSharp.PostMessage()` and I can catch it in ` OnBrowserJavascriptMessageReceived` event. (Also going to fix the TypeError.)
I can use the `SchemeHandler` to check if that URL is allowed (or banned).
 - Show it if url is allowed.
 - Do not show it if url is banned.
 - Ask user for permission to display notifications (if url is not on both of the allowed & banned lists).

**Comment by Haltroy** [comment]
I created my own polyfill and it seems to work (without `then` function).
I have to find a way to implement that.
1. Korot injects a variable named `korotNotificationPermission` and its set to `granted`/`denied`/`unknown` at start then injects the `notification.js`.
2. `notification.js` creates `CefSharp.PostMessage` calls (on creating a new notification) which looks similar like this:

       // For sending a notification
       "[Korot.Notification Message="" Dir="" Lang="" Badge=""  Body="" Tag="" Icon="" Image="" Data="" Vibrate="" Renotify="" RequireInteraction="" Actions="" Silent="" /]"	
       //For asking permission (denied/unknown)
       "[Korot.RequestNotification]"

3. `OnBrowserJavascriptMessageReceived` will catch the requests and translates it to XML format and reads the XmlNode.
It will simply prompt user if they want to see notifications if `unknown`. If user allows it, then refresh the page so website is loaded with the new variable. Then goes back to 1.
4. Then checks if the conditions are nice (granted etc.).
5. Shows the notification.

**Comment by Haltroy** [comment]
I did it.
